### ISSUE TITLE
Using esphome core helper functions in lambdas

### ISSUE THREAD

**Issue by dudanov** [esphome/esphome-project-template#4]
In this YAML I want use ``remap`` template function from ``esphome/core/helpers.h``. Local build is successfull, but ``esphome/build-action`` fails.

yaml:

```
number:
  - platform: template
    name: Hands Sensor Sensitivity
    icon: mdi:signal-distance-variant
    entity_category: config
    mode: slider
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: 10
    step: 0.5
    on_value:
    - output.set_level:
        id: hands_sensor
        level: !lambda "return esphome::remap(x, 1.0f, 10.0f, id(hands_sensor).get_min_power(), id(hands_sensor).get_max_power());"
```

Log:
```
monochrome-delay.yaml: In lambda function:
monochrome-delay.yaml:171:14: error: 'remap' is not a member of 'esphome'
```
